server:
  port: 8075

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: someone
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  access:
    key: 7#70OZn0#Dsaodi98BK8C1%T&hBnrzgqK28o
    expiration-time: 86400000
  refresh:
    key: 7787dsa8dp7#%70OZ()BK8C1%Taskldjksal***
    expiration-time: 604800000

logging:
  file:
    name: orders.log

app:
  admin:
    password: asad7167
    firstName: "turgunboyev791@gmail.com"

